"""Created table Production

Revision ID: 349b6d823b55
Revises: c04f0e0e8daf
Create Date: 2023-05-05 01:32:45.147126

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '349b6d823b55'
down_revision = 'c04f0e0e8daf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
